name: Secrets Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output some secret
        env:
          USERNAME: ${{ secrets.CREDENTIALS['username'] }}
        run: |
          echo "My username is $USERNAME"
