name: Secrets Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output Secret
        run: |
          echo "Next line has my username"
          USERNAME=$(echo '${{ secrets.credentials }}' | jq -r '.username')
          echo "Username is $USERNAME"
